# Generated by Django 3.1.2 on 2020-10-17 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('phonenumber', models.IntegerField()),
                ('email', models.EmailField(max_length=255)),
                ('role', models.BooleanField(default=False)),
            ],
        ),
    ]
